spring:
  #\u6570\u636E\u5E93\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/esstudy?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: 146270

    # jpa \u9ED8\u8BA4\u91C7\u7528 hikari \u6570\u636E\u6E90\u4E13\u7528\u914D\u7F6E
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  # jpa \u76F8\u5173\u914D\u7F6E
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # \u6570\u636E\u5E93\u65B9\u8A00
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application

  #mvc
  mvc:
    static-path-pattern: /**

    # \u9759\u6001\u8D44\u6E90\u70ED\u90E8\u7F72
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: static/**

  # \u65E5\u671F\u683C\u5F0F\u5316
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

